server:
  port: 8090
  forward-headers-strategy: framework
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/halo
    username: root
    password: mysql830
  output:
    ansi:
      enabled: detect
  #r2dbc:
  #  url: r2dbc:pool:mysql://127.0.0.1:3306/halo
  #  username: root
  #  password: mysql830
  sql:
    init:
      mode: always
      platform: mysql
  codec:
    max-in-memory-size: 10MB
  messages:
    basename: config.i18n.messages
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
  thymeleaf:
    reactive:
      maxChunkSize: 8KB
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=1h, maximumSize=10000

halo:
  work-dir: ${user.home}/.halo2
  attachment:
    resource-mappings:
      - pathPattern: /upload/**
        locations:
          - migrate-from-1.x

springdoc:
  api-docs:
    enabled: false
  writer-with-order-by-keys: true

logging:
  file:
    name: ${halo.work-dir}/logs/halo.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true

resilience4j.ratelimiter:
  configs:
    authentication:
      limitForPeriod: 3
      limitRefreshPeriod: 1m
      timeoutDuration: 0
    comment-creation:
      limitForPeriod: 10
      limitRefreshPeriod: 1m
      timeoutDuration: 0s
    signup:
      limitForPeriod: 3
      limitRefreshPeriod: 1h
      timeoutDuration: 0s
    send-email-verification-code:
      limitForPeriod: 1
      limitRefreshPeriod: 1m
      timeoutDuration: 0s
    verify-email:
      limitForPeriod: 3
      limitRefreshPeriod: 1h
      timeoutDuration: 0s
    send-reset-password-email:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 0s
